services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./configs:/freqtrade/configs"
      - "./${FREQTRADE__STRATEGY:-NostalgiaForInfinityX7}.py:/freqtrade/${FREQTRADE__STRATEGY:-NostalgiaForInfinityX7}.py"
    ports:
      - "${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"
    # Default command used when running `docker compose up`
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    env_file:
      - path: .env
        required: false # default true
    command: >
      trade
      --strategy-path .
      -v
