name: Sync Fork

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          upstream_sync_repo: iterativv/NostalgiaForInfinity
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
