name: Sync Fork

on:
  schedule:
    - cron: "0 */6 * * *" # 6 tiếng chạy 1 lần
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: iterativv/NostalgiaForInfinity
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
